### ISSUE TITLE
您好  在train的时候没有问题  为什么在sample的时候出现了这个错误呢     ckpt为什么是空的呢   

### ISSUE THREAD

**Issue by liang23333** [xue2han/AncientChinesePoemRNN#1]
C:\LAWHCA\prime>python sample.py
WARNING:tensorflow:From sample.py:35 in sample.: initialize_all_variables (from
tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03
-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
WARNING:tensorflow:From sample.py:36 in sample.: all_variables (from tensorflow.
python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
WARNING:tensorflow:reached end of file
WARNING:tensorflow:save\checkpoint: Checkpoint ignored
None
Traceback (most recent call last):
  File "sample.py", line 45, in <module>
    main()
  File "sample.py", line 26, in main
    sample(args)
  File "sample.py", line 39, in sample
    print(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

C:\LAWHCA\prime>

**Comment by xue2han** [comment]
因为这份代码是基于tensorflow 0.11版本编写的，而你可能使用了更新的版本。
