### ISSUE TITLE
诗句中有* 或英文字母是为什么呢

### ISSUE THREAD

**Issue by dangbo** [xue2han/AncientChinesePoemRNN#6]
`风入洞庭累，和名匪并亲。日作禅楼末，丽慨*稚*。`
`风烂嵯峨古十旬，和音写断围中盏。日见春风又满林，丽句君邀**名。`
`有尽众一身，爱他遗便素。千龄何累休一会，两f啸琴却前归。`

**Comment by xue2han** [comment]
你仔细看一下源码，*代表未知字符。至于英文字符，是因为数据集没有处理干净，里面包含了一些英文字符。

**Comment by dangbo** [comment]
thx
